version: 2.1

orbs:
  win: circleci/windows@5.0
  macos: circleci/macos@2.4

commands:
  run-cibuildwheel:
    parameters:
      cibw-version:
        type: string
        default: 2.21.2
    steps:
      - run:
          name: run cibuildwheel
          shell: bash -eo pipefail
          command: |
            if [[ $OS == Windows_NT ]]; then
              python -m pip install --user cibuildwheel==<< parameters.cibw-version >>
              python -m cibuildwheel --output-dir dist
            else
              python3 -m pip install --user cibuildwheel==<< parameters.cibw-version >>
              python3 -m cibuildwheel --output-dir dist
            fi

      - store_artifacts: &store-artifacts
          path: ./dist
      - persist_to_workspace: &persist-to-workspace
          root: ./dist/
          paths: .

environment: &global-environment
  PIP_PROGRESS_BAR: 'off'

jobs:
  build-linux:
    parameters:
      python-version:
        type: string

    docker:
      - image: cimg/python:3.12

    environment:
      <<: *global-environment
      CIBW_PROJECT_REQUIRES_PYTHON: ~=<< parameters.python-version>>
      CIBW_ARCHS_LINUX: x86_64

    steps:
      - checkout
      - setup_remote_docker
      - run-cibuildwheel

  build-linux-aarch64:
    parameters:
      python-version:
        type: string

    machine:
      image: default

    resource_class: arm.medium

    environment:
      <<: *global-environment
      CIBW_PROJECT_REQUIRES_PYTHON: ~=<< parameters.python-version>>
      CIBW_ARCHS_LINUX: aarch64

    steps:
      - checkout
      - run-cibuildwheel

  build-osx:
    parameters:
      python-version:
        type: string
      xcode:
        type: string
        default: "14.3.0"

    resource_class: macos.m1.medium.gen1

    macos:
      xcode: << parameters.xcode >>

    environment:
      <<: *global-environment
      CIBW_PROJECT_REQUIRES_PYTHON: ~=<< parameters.python-version>>

    steps:
      - checkout
      - macos/install-rosetta
      - run-cibuildwheel

  build-sdist:
    docker:
      - image: cimg/python:3.12

    steps:
      - checkout
      - run:
          name: build sdist
          command: |
            python -m venv env
            . env/bin/activate
            pip install -r requirements.txt
            pip install setuptools --upgrade
            python dwave/gate/simulator/operation_generation.py
            python setup.py sdist -d ./dist
      - store_artifacts: *store-artifacts
      - persist_to_workspace: *persist-to-workspace

  build-windows:
    parameters:
      python-version:
        type: string

    executor:
      name: win/default

    environment:
      <<: *global-environment
      CIBW_PROJECT_REQUIRES_PYTHON: ~=<< parameters.python-version>>
      CIBW_ARCHS_WINDOWS: AMD64

    steps:
      - checkout
      - run-cibuildwheel

  deploy-all:
    docker:
      - image: cimg/python:3.12

    steps:
      - attach_workspace:
          at: dist

      - store_artifacts:
          path: ./dist

      - run:
          name: deploy
          command: |
            python -m venv env
            . env/bin/activate
            python -m pip install twine
            twine upload -u "$PYPI_USERNAME" -p "$PYPI_PASSWORD" --skip-existing ./dist/*

  # we could do this as part of the various test jobs but getting the pathing
  # and configuration to work correctly is a pain. And since there is not
  # significant different between the linux/osx/windows code I think it
  # suffices to just do it once
  test-codecov:
    docker:
      - image: cimg/python:3.12

    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            python -m venv env
            . env/bin/activate
            pip install -r requirements.txt
            pip install -r requirements_dev.txt
      - run: &unix-build
          name: build
          command: |
            . env/bin/activate
            python dwave/gate/simulator/operation_generation.py
            pip install .
      - run:
          name: run coverage
          command: |
            . env/bin/activate
            pytest tests/ --cov=dwave.gate
      - run:
          name: codecov
          command: |
            . env/bin/activate
            pip install codecov
            codecov

  test-sdist:
    docker:
      - image: cimg/python:3.12

    steps:
      - checkout
      - attach_workspace:
          at: dist
      - run:
          name: install from sdist
          command: |
            python -m venv env
            . env/bin/activate
            pip install dist/dwave_gate*.tar.gz
      - run:
          name: run tests
          command: |
            . env/bin/activate
            pip install -r requirements_dev.txt
            pytest tests/

  test-dependencies:
    parameters:
      python-version:
        type: string
      dependency-versions:
        type: string

    docker:
      - image: python:<< parameters.python-version >>-slim

    steps:
      - checkout
      - attach_workspace:
          at: dist
      - run:
          name: install
          command: |
            python -m venv env
            . env/bin/activate
            pip install "<< parameters.dependency-versions >>" --upgrade --only-binary=numpy
            pip install dwave-gate --no-index -f dist/ --no-deps --force-reinstall
      - run: &unix-run-tests
          name: run tests
          command: |
            . env/bin/activate
            pip install -r requirements_dev.txt
            pytest tests/
workflows:
  tests:
    jobs:
      - build-linux: &build
          matrix:
            parameters:
              python-version: &python-versions [3.9.19, 3.10.14, 3.11.9, 3.12.4, 3.13.0]
      - build-linux-aarch64: *build
      - build-sdist
      - build-osx: *build
      - build-windows: *build
      - test-codecov
      - test-dependencies:
          name: test-dependencies - << matrix.dependency-versions >> - py << matrix.python-version >>
          requires:
            - build-linux
          matrix:
            parameters:
              # test the lowest and highest for each dependency
              dependency-versions: [
                numpy==1.24.4,
                numpy
              ]
              python-version: *python-versions
            exclude:
              - dependency-versions: numpy==1.24.4
                python-version: 3.12.4
              - dependency-versions: numpy==1.24.4
                python-version: 3.13.0
      - test-sdist:
          requires:
            - build-sdist
  deploy:
    jobs:
      - build-linux: &deploy-build
          <<: *build
          filters:
            tags:
              only: /^[0-9]+(\.[0-9]+)*((\.dev|rc)([0-9]+)?)?$/
            branches:
              ignore: /.*/
      - build-linux-aarch64: *deploy-build
      - build-osx: *deploy-build
      - build-sdist:
          filters:
            tags:
              only: /^[0-9]+(\.[0-9]+)*((\.dev|rc)([0-9]+)?)?$/
            branches:
              ignore: /.*/
      - build-windows: *deploy-build
      - deploy-all:
          filters:
            tags:
              only: /^[0-9]+(\.[0-9]+)*((\.dev|rc)([0-9]+)?)?$/
            branches:
              ignore: /.*/
          requires:
            - build-linux
            - build-linux-aarch64
            - build-osx
            - build-sdist
            - build-windows
